/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d6ece31d-d953-4ece-b26b-5688e855f892",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_LcsBBrciK",
    "aws_user_pools_web_client_id": "2rgenrg2ff0tlc6o5mgcavq4ib",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pynsn7766ncrfldxkdrkxztgym.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-f57wg5j3efajdn2xbr4ed72hba",
    "aws_user_files_s3_bucket": "amplifyapp69f8b345498a4e2ebb51ee994018b23502947-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
